### ISSUE TITLE
ChatSecure doesn't compile with AFNetworking Version 2.4

### ISSUE THREAD

**Issue by zhangtemplar** [ChatSecure/ChatSecure-iOS#375]
I tried to compile ChatSecure recently. However Xcode reports compilation error: 
```
/Users/xxx/Documents/ChatSecure-iOS/ChatSecure/Classes/Utilities/OTRCertificatePinning.m:76:29: Property 'validatesCertificateChain' not found on object of type 'AFSecurityPolicy *'
```

After checking the AFNetworking, I found the Property 'validatesCertificateChain' is removed from 'AFSecurityPolicy' in the latest AFNetworking (2.4). However, 'validatesCertificateChain' still exists in 'AFSecurityPolicy' in version up to 2.3.1

**Comment by chrisballinger** [comment]
Run a `pod install` to update to the latest version

**Comment by zhangtemplar** [comment]
@chrisballinger do you mean the "develop" branch? I am already up to date with "master" branch.

**Comment by chrisballinger** [comment]
sure, however, develop is unstable and will be changing significantly in
the upcoming weeks

**Comment by chrisballinger** [comment]
Closing this for now, let us know if you have any other issues
